media:
  input: src/assets/ms_notes
  output: src/assets/ms_notes

content:
  - name: ms_notes
    label: MS Notes
    type: collection
    path: src/content/ms_notes
    icon: book
    filename: '{fields.lectureNumber}-{fields.lecture_title}.md'
    fields:
      - name: lecture_title
        label: Lecture Title
        type: string
      - name: lecture_description
        label: Lecture Description
        type: text
      - name: pubDate
        label: Publication Date
        type: date
      - name: lecture_draft
        label: Draft
        type: boolean
        default: true
      - name: lectureNumber
        label: Lecture Number
        type: string
      - name: subject
        label: Subject
        type: string
      - name: body
        label: Content
        type: rich-text
